### ISSUE TITLE
Dealing with C Dependencies on Linux

### ISSUE THREAD

**Issue by leogdion** [SwiftPackageIndex/SwiftPackageIndex-Server#837]
It looks like my latest library [MistKit](https://github.com/brightdigit/MistKit) uses [Fluent](https://github.com/vapor/fluent) which requires sqlite c libraries. This is causing a [build failure.](https://swiftpackageindex.com/builds/6A8E0797-AD08-4134-8C01-D7A9A2A69084)

Is there a way to specify these dependencies? i.e. `apt install libsqlite3-dev`

**Comment by finestructure** [comment]
Hi Leo, there is a way, by setting up docker images with the dependency installed which we then add to our allow-list. The "Images on Linux" part of this blog post has more detail: https://blog.swiftpackageindex.com/posts/the-swift-package-index-metadata-file-first-steps/

Let me know if that helps!

**Comment by leogdion** [comment]
Awesome! Thank you.

I pushed a docker image for `libsqlite3-dev` to the docker hub, using this tutorial:
https://docs.docker.com/docker-hub/

I added the `.spi.yml` file to my repo at this branch as well:
https://github.com/brightdigit/MistKit/tree/feature/linux-sqlite-dep

Does it need to be on `main` and a new release to test it out?

**Comment by finestructure** [comment]
I've just prepared the config change on our end, which we'll roll out shortly. One thing you'd have to change regarding the image that I forgot to mention: We require image tags (i.e. version suffixes).

So instead of using an untagged image `image: leogdion/mistkit-swift` you should tag it for the Swift version(s) you're supporting:

```
docker build -t leogdion/mistkit-swift:5.3 .
docker push leogdion/mistkit-swift:5.3
```

and update `.spi.yml` to

```
    swift_version: '5.3'
    image: leogdion/mistkit-swift:5.3
```

This will also allow you to change the `FROM swift:5.4` when the time comes and push that as `leogdion/mistkit-swift:5.4` with a matching section for `swift_version: '5.4'`.

**Comment by leogdion** [comment]
Thanks for heads up!

I updated spi file as well as the image to ‘brightdigit/mistkit-sql’. There are different tags for Swift versions as well as Ubuntu.

Please let me know if you need anything else.
https://github.com/brightdigit/MistKit/tree/feature/linux-sqlite-dep

**Comment by finestructure** [comment]
New image still not being picked up. Everything seems to be in order, need to follow up to see what's going on.

https://swiftpackageindex.com/builds/4678AC13-B82A-4BC1-966C-A338C3CB3635

**Comment by finestructure** [comment]
It's working exactly as it should locally:

```
(lldb) po image
▿ Optional<String>
  - some : "brightdigit/mistkit-sql:5.3-focal"

(lldb) po cmd.self
▿ ShellOutCommand
  - string : "/usr/local/bin/docker run --rm -v \"$PWD\":/host -w /host brightdigit/mistkit-sql:5.3-focal swift build --enable-test-discovery"

Running build ...
/usr/local/bin/docker run --rm -v "$PWD":/host -w /host brightdigit/mistkit-sql:5.3-focal swift build --enable-test-discovery
```

Need to see if there's been a deployment issue.

**Comment by finestructure** [comment]
I've added some internal logging, re-deployed, and re-triggered the build. Should update soon, let's see if that changes things.

**Comment by leogdion** [comment]
<img width="854" alt="Screen Shot 2020-12-09 at 11 28 27 AM" src="https://user-images.githubusercontent.com/1036388/101657254-aad6f000-3a11-11eb-9ef7-001ce87103f5.png">
🥳  Looks like it worked. I think this issue can be closed unless you think otherwise.

**Comment by finestructure** [comment]
Ah great! No idea what happened exactly previously but I guess "rebooting" always helps =)
